-- 코드를 입력하세요 ins 보호시작 out 입양일 
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID // id로 같다
WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME // 조건은 where에다가
ORDER BY ANIMAL_INS.DATETIME ASC
